export const images = {
  logo: "/codewp-logo.png",
  heroStudent: "/opt/IMG_2629.jpg",
  volunteerHelp: "/opt/IMG_2624.jpg",
  codingLaptop: "/opt/coding-laptop.jpg",
  congressLetter: "/opt/congress-letter.jpg",
  danvilleSanRamon: "/opt/danville-san-ramon.jpg",
  pythonCourse: "/python-course.png",
  vibecodingCourse: "/vibecoding-course.png",
  promoVideo: "/promo.mp4",
  /** The 38s photo film on /about, rendered with Remotion from the team's own
   *  photos. It replaced promo.mp4 there; that file is kept for anything still
   *  linking to it. */
  storyVideo: "/story.mp4",
  team: {
    shreyan: "/team-shreyan.jpg",
    samanyu: "/team-samanyu.jpg",
    bhim: "/bhim.jpeg",
    naman: "/team-naman.jpg",
    om: "/team-om.jpeg",
    darsh: "/team-darsh.png",
    trey: "/team-trey.jpg",
    sirish: "/team-sirish.jpg",
    aakash: "/team-aakash.png",
    aadi: "/team-aadi.webp",
    prithvi: "/team-prithvi.jpg",
    sanjay: "/team-sanjay.jpg",
    hannah: "/team-hannah.jpeg",
    vetri: "/team-vetri.png",
    mithra: "/team-mithra.jpeg",
    nehha: "/Nehha-team.jpeg",
    manit: "/manit.jpg",
    rachit: "/team-rachit.png",
    svanik: "/team-svanik.png",
    vibhav: "/team-vibhav.jpg",
  },
  gallery: [
    { src: "/opt/IMG_2625.jpg", width: 1050, height: 1400, alt: "In the classroom" },
    { src: "/opt/IMG_2784.jpg", width: 1400, height: 1050, alt: "Hands-on learning" },
    { src: "/opt/IMG_2782.jpg", width: 1400, height: 1050, alt: "Smiling student" },
    { src: "/opt/IMG_2789.jpg", width: 1050, height: 1400, alt: "Students coding" },
    { src: "/opt/IMG_2631.jpg", width: 1050, height: 1400, alt: "Volunteer presenting" },
    { src: "/opt/IMG_2795.jpg", width: 1050, height: 1400, alt: "Students at booth" },
    { src: "/opt/IMG_2787.jpg", width: 1050, height: 1400, alt: "Crowded workshop" },
    { src: "/opt/IMG_2790.jpg", width: 1050, height: 1400, alt: "End of session" },
    { src: "/opt/IMG_2619.jpg", width: 1050, height: 1400, alt: "Students learning together" },
    { src: "/opt/IMG_2622.jpg", width: 1050, height: 1400, alt: "Workshop session" },
    { src: "/opt/IMG_2630.jpg", width: 1050, height: 1400, alt: "Coding at laptops" },
    { src: "/opt/IMG_3652.jpg", width: 1050, height: 1400, alt: "Advanced Python workshop" },
  ],
  dublinHackathon: [
    {
      src: "/opt/dublin-hackathon-teams.jpg", width: 1800, height: 1200,
      alt: "Students collaborate around a laptop at the Dublin hackathon",
    },
    {
      src: "/opt/dublin-hackathon-pair.jpg", width: 1800, height: 1200,
      alt: "Two students work side by side on their laptops at the Dublin hackathon",
    },
    {
      src: "/opt/dublin-hackathon-builder.jpg", width: 1800, height: 1200,
      alt: "A student works on a laptop during the Dublin hackathon",
    },
    {
      src: "/opt/dublin-hackathon-candid.jpg", width: 1800, height: 1200,
      alt: "A student reacts with delight during the Dublin hackathon",
    },
    {
      src: "/opt/dublin-hackathon-whiteboard.jpg", width: 1800, height: 1200,
      alt: "Two students sketch out an idea together at the Dublin hackathon",
    },
    {
      src: "/opt/dublin-hackathon-banner.jpg", width: 1800, height: 1200,
      alt: "A student stands beside a CodeWithPurpose banner at the Dublin hackathon",
    },
  ],
} as const;
