export const images = {
  logo: "/codewp-logo.png",
  heroStudent: "/images/IMG_2629.jpeg",
  volunteerHelp: "/images/IMG_2624.jpeg",
  codingLaptop: "/coding-laptop.jpg",
  congressLetter: "/HOR.png",
  danvilleSanRamon: "/DanvillSanRamon.png",
  pythonCourse: "/python-course.png",
  vibecodingCourse: "/vibecoding-course.png",
  promoVideo: "/promo.mp4",
  team: {
    shreyan: "/shreyan.jpg",
    samanyu: "/samanyu.jpeg",
    bhim: "/bhim.jpeg",
    naman: "/naman.png",
    prithvi: "/prithvi.png",
  },
  gallery: [
    { src: "/images/IMG_2625.jpeg", alt: "In the classroom" },
    { src: "/images/IMG_2784.jpg", alt: "Hands-on learning" },
    { src: "/images/IMG_2782.jpg", alt: "Smiling student" },
    { src: "/images/IMG_2789.jpg", alt: "Students coding" },
    { src: "/images/IMG_2631.jpeg", alt: "Volunteer presenting" },
    { src: "/images/IMG_2795.jpg", alt: "Students at booth" },
    { src: "/images/IMG_2787.jpg", alt: "Crowded workshop" },
    { src: "/images/IMG_2790.jpg", alt: "End of session" },
    { src: "/images/IMG_2619.jpeg", alt: "Students learning together" },
    { src: "/images/IMG_2622.jpeg", alt: "Workshop session" },
    { src: "/images/IMG_2630.jpeg", alt: "Coding at laptops" },
    { src: "/images/IMG_3652.jpeg", alt: "Advanced Python workshop" },
  ],
  stats: ["/2.png", "/3.png", "/4.png"],
} as const;
